Opal.queue(function(Opal) {/* Generated by Opal 1.7.1 */
  var $def = Opal.def, $return_val = Opal.return_val, self = Opal.top, nil = Opal.nil;

  
  
  $def(self, '$js_image', function $$js_image(parent, path) {
    
    
var div = document.getElementById(parent);
var canvas = document.createElement("canvas");
canvas.width = div.clientWidth;
canvas.height = div.clientHeight;
canvas_id=parent+'_canvas';
canvas.id = canvas_id;
div.appendChild(canvas);
var img = new Image();
img.src = path;
img.onload = function() {
    // Créer un canvas et y ajouter l'image
    var canvas = new fabric.Canvas(canvas_id);
    var image = new fabric.Image(img);
    canvas.add(image);

    // Appliquer un filtre de colorisation rouge
    image.filters.push(new fabric.Image.filters.BlendColor({
        color: '#FF0000',
        opacity: 0.5
    }));
    image.applyFilters();
    // Afficher l'image colorisée sur le canvas
    canvas.renderAll();
}



  });
  
  $def(self, '$js_tint', $return_val(nil));
  const Fabric_canvas={};
  //

var div = document.getElementById('view');
var canvas = document.createElement("canvas");
canvas.width = div.clientWidth;
canvas.height = div.clientHeight;
canvas_id='_canvas';
canvas.id = canvas_id;
div.appendChild(canvas);
var img = new Image();
img.src = './medias/images/3D.jpg';
img.onload = function() {
    var fab_canvas = new fabric.Canvas(canvas_id);
//fab_canvas.set('id', 'myCanvasId');
Fabric_canvas.myCanvasId=fab_canvas
    var image = new fabric.Image(img);
image.hasControls = false;
image.selectable = false;
image.hoverCursor = 'default';
image.evented = false;
 image.id= 'myImageId';
    fab_canvas.add(image);
  fab_canvas.getObjects().forEach(function(o) {
          if(o.id == 'myImageId') {
              //console.log(o.id)
o.filters.push(new fabric.Image.filters.BlendColor({color: 'red'}));
o.applyFilters();
          }
      })
}


setTimeout(() => {


  console.log("Delayed for 1 second.");
var getted_canvas = Fabric_canvas.myCanvasId
getted_canvas.selection = false
var rect = new fabric.Rect({
  left: 100,
  top: 100,
  fill: 'blue',
  width: 20,
  height: 20,
  angle: 45

});

getted_canvas.add(rect);
   getted_canvas.getObjects().forEach(function(o) {
          if(o.id == 'myImageId') {
delete o.filters[0];

o.filters.push(new fabric.Image.filters.BlendColor({color: 'pink'}));
o.applyFilters();
          }
      })

}, 1000)

;
});
